### ISSUE TITLE
Mêmes tailles pour exports PNG des logos

### ISSUE THREAD

**Issue by AntoineAugusti** [entrepreneur-interet-general/design-system#4]
Ma Semaine utilise les logos EIG 3, en version PNG (car ils sont inclus dans les e-mails). Les exports en PNG n'ont pas tous la même taille, ce qui rend étrange sur les interfaces.

L'idée serait donc d'avoir des exports en PNG des logos à un format constant, par exemple 250x250

**Comment by jbledevehat** [comment]
Fait en taille 240x240

**Comment by AntoineAugusti** [comment]
Merci, mis à jour dans l'autre repo https://github.com/entrepreneur-interet-general/ma-semaine/commit/66f11456ef0576f46ef6de63ea3daa3c5cfdf478?diff=split&short_path=de1bd83#diff-de1bd832f961efb306213f6c1fefc961
